project 'Presentation.xcodeproj'

platform :ios, '13.0'
use_frameworks!
inhibit_all_warnings!
workspace 'OpenWeather'

target 'OpenWeather' do
  project 'Presentation/Presentation.xcodeproj'
  pod 'Reusable', '= 4.1.0'
  pod 'Infrastructure', :path => './Infrastructure/'
  pod 'Domain', :path => './Domain/'
  pod 'SDWebImage', '= 5.5.2'
  
  target "PresentationTests" do
    pod 'Quick', '= 2.2.0'
    pod 'Nimble', '= 8.0.5'
  end
end

target 'Infrastructure' do
  project 'Infrastructure/Infrastructure.xcodeproj'
  pod 'Alamofire', '= 5.0.2'
  pod 'CodableAlamofire', '= 1.2.0'
  pod 'Domain', :path => './Domain/'
  
  target "InfrastructureTests" do
    pod 'Quick', '= 2.2.0'
    pod 'Nimble', '= 8.0.5'
  end
end

target 'Domain' do
  project 'Domain/Domain.xcodeproj'
  
  target "DomainTests" do
    pod 'Quick', '= 2.2.0'
    pod 'Nimble', '= 8.0.5'
  end
end

post_install do |installer|
  require 'fileutils'
  FileUtils.cp_r('Pods/Target Support Files/Pods-OpenWeather/Pods-OpenWeather-acknowledgements.plist',
                 'Presentation/Settings.bundle/Acknowledgements.plist', :remove_destination => true)
                 installer.pods_project.targets.each do |target|
                   target.build_configurations.each do |config|
                     config.build_settings['SWIFT_VERSION'] = '5.0'
                   end
                 end
end
